version: '3.8'

services:
  wordpress:
    build:
      context: .
      dockerfile: ./Dockerfile.wordpress
    image: wordpress:latest
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ${WORDPRESS_SITE_NAME}_wordpress_data:/var/www/html
    env_file:
      - stack.env

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${WORDPRESS_SITE_NAME}_mysql_data:/var/lib/mysql
    env_file:
      - stack.env

volumes:
  wordpress_data:
    driver: local
  mysql_data:
    driver: local

